pipeline {
  agent any
  tools {
    nodejs 'node-18.19.0'
  }

  environment {
    REMOTE_SERVER = "172.31.22.96" //  server IP
    CONTAINER_NAME = 'applauncher'
    AWS_REGION = 'us-east-1' // Replace with your desired AWS region
    ECR_REPO = 'poc-marketplace' // Replace with your ECR repository name
    IMAGE_TAG = "prod.applauncher.${env.BUILD_NUMBER}"    // add  image name 
    HTTP_PORT = '8033'    //change the port
    DEPLOYMENT_KEY='marketplace deployment key'  
  } // end of environment 

  stages {
   
    stage('Install Dependencies') {
      steps {
        sh 'npm ci'
      }
    }

  stage('Build Docker Image') {
    steps {
        script {
            withAWS(region: AWS_REGION, credentials: 'wm-ps-user-ecr') {
                def awsAccountID = sh(returnStdout: true, script: "aws sts get-caller-identity --query Account --output text").trim()
                
                // Login to AWS ECR
                sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${awsAccountID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
                
                // Build Docker image
                sh "docker buildx build --tag=${ECR_REPO}:${IMAGE_TAG} ."
            }
        }
    }
}


    stage('Push to Docker Hub') {
      steps {
        script {
          withAWS(region: AWS_REGION, credentials: 'wm-ps-user-ecr') {
            def awsAccountID = sh(returnStdout: true, script: "aws sts get-caller-identity --query Account --output text").trim()
            //def ecrLogin = sh(returnStdout: true, script: "aws ecr get-login --no-include-email --region ${AWS_REGION}")
            //sh "${ecrLogin}"
            // Login to AWS ECR
                sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${awsAccountID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
            
            // Tag and push Docker image to ECR
            sh "docker tag ${ECR_REPO}:${IMAGE_TAG} ${awsAccountID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"
            sh "docker push ${awsAccountID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"
          }
        }
      }
    } 

    stage('Deploy Docker Container') {
      steps {
        script {
          sshagent([DEPLOYMENT_KEY]) {
            withAWS(region: AWS_REGION, credentials: 'wm-ps-user-ecr') {
              def awsAccountID = sh(returnStdout: true, script: "aws sts get-caller-identity --query Account --output text").trim()
              def containerExists = sh(returnStdout: true, script: "ssh -o StrictHostKeyChecking=no ubuntu@${REMOTE_SERVER} 'docker ps -a --filter name=${CONTAINER_NAME} --format \"{{.Names}}\"'")
              
              // Stop and remove the existing container if it exists
              if (containerExists.trim() != '') {
                sh "ssh -o StrictHostKeyChecking=no ubuntu@${REMOTE_SERVER} 'docker rm -f ${CONTAINER_NAME}'"
                echo "Container deleted: ${CONTAINER_NAME}"
              }
              // comment old code
              // def ecrLogin = sh(returnStdout: true, script: "aws ecr get-login --no-include-email --region ${AWS_REGION}")
             // sh "ssh -o StrictHostKeyChecking=no ubuntu@${REMOTE_SERVER} '${ecrLogin}'"

              // Get ECR login command
                    def ecrLogin = sh(returnStdout: true, script: "aws ecr get-login-password --region ${AWS_REGION}")
                    // Print the ECR login command value
                     echo "ECR Login Command: ${ecrLogin}"
                    // Run SSH command to authenticate Docker on remote server
                    sh """
                        ssh -o StrictHostKeyChecking=no ubuntu@${REMOTE_SERVER} '
                            echo "${ecrLogin}" | docker login --username AWS --password-stdin ${awsAccountID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                        '
                    """

              // Pull and run the new Docker image on the remote server
              sh "ssh -o StrictHostKeyChecking=no ubuntu@${REMOTE_SERVER} 'docker pull ${awsAccountID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}'"
              sh "ssh -o StrictHostKeyChecking=no ubuntu@${REMOTE_SERVER} 'docker run -d --name ${CONTAINER_NAME} -p ${HTTP_PORT}:7001 ${awsAccountID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}'"
            }
          }
        }
      } 
    } 
  }
}
